### ISSUE TITLE
Loader

### ISSUE THREAD

**Issue by 89gsc** [desta88/Codeigniter-Barcode#1]
I had to change your class file to this to make it work: 

<?php
if (!defined('BASEPATH')) {
    exit('No direct script access allowed');
}

class Zend {
    public function __construct($class = NULL) {
        ini_set('include_path', ini_get('include_path') . PATH_SEPARATOR . APPPATH . 'libraries');
        if ($class) {
            require_once (string) $class . ".php";
            log_message('debug', "Zend Class $class Loaded");
        } else {
            log_message('debug', "Zend Class Initialized");
        }
    }
    public function load($sClassName) {
        require_once (string) $sClassName . ".php";
        log_message('debug', "-> Zend Class $sClassName Loaded from the library");
    }
}

Having it as EXT would fail on my setup, I don't know if its PHP version or CI 3 I am using that caused this. But thanks for your hard work on this library.

**Comment by desta88** [comment]
@lilsammy Yeah, I was think that's issue from codeigniter, because this is running by CodeIgniter Version 2.1.4, I'm never try to CI 3 but I'll try later. 

And EXT constant for filename extensions in this new CodeIgniter version, the EXT constant has been removed, see this tutorial http://www.codeigniter.com/userguide3/installation/upgrade_300.html (see the part of The EXT constant). 

Thanks a lot for your contribution

**Comment by desta88** [comment]
I've been updated the loader class..
Check it now @lilsammy

**Comment by kallol24** [comment]
Hey its not working bro
Can you please update I am using CI 3.1.0
